const GITHUB_AUTH_TOKEN = "ghpQRCuBQopHTJMxDMqnQfh9hriB3lzb94gLfcO"
const BOT_NUMBER = "94784331180"
const SESSION_ID = "PRABATH-MD~V3VFxRJB#yc0XOqcCy372JCERxoi3OnYtWKdsdp7DJyfn28coSU4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
