const GITHUB_AUTH_TOKEN = "ghpQRCuBQopHTJMxDMqnQfh9hriB3lzb94gLfcO"
const BOT_NUMBER = "94784331180"
const SESSION_ID = "PRABATH-MD~cilCBYyS#3lOFvNWVaDrfL-Rtw-Z_IISq-XU7kA_Q7zlKDWMh6I4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
